config/routes.rb
Rails.application.routes.draw do
  
  resources :leads
  resources :feeds do 
    collection { post :import }
  end

  resources :locations
  resources :app_data
  resources :mobile_apps
  resources :agencies
  resources :domain_alexas
  resources :news
  resources :companies do 
    collection { post :import }
  end
  resources :categories
  resources :domains do 
    collection { post :import }
    collection { get :autocomplete }
  end
  resources :daycares
  resources :blogs
  resources :linkedin_counts do
    collection { post :import }
  end
  ActiveAdmin.routes(self)
  devise_for :users

  as :user do
  	get "signin" => 'devise/sessions#new'
  	delete "signout" => 'devise/sessions#destroy'
  	get "signup" => 'devise/registrations#new'
  end

  root 'pages#home'

  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'
  get 'uploads' => 'pages#uploads'
  get 'talent' => 'pages#talent'

  get 'emails' => 'pages#emails'

  get 'sitemap' => 'pages#sitemap'
  get 'for_providers' => 'pages#for_providers'
  get 'dashboard' => 'pages#dashboard'
  get 'privacy_policy' => 'pages#privacy_policy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'loaderio-5d6ea8f06b52a5188451d2d277efab90' => 'pages#loader'

end

app/models/feed.rb
class Feed < ApplicationRecord
	acts_as_taggable_on :tags
	geocoded_by :address

	after_validation :geocode, :if => :address_changed?

	has_many :news
	has_and_belongs_to_many :categories

	validates :follow_url, uniqueness: true

	searchkick

	def self.to_csv(options= {})
  	CSV.generate(options) do |csv|
  		csv << column_names

  		all.each do |c|
  			csv << c.attributes.values_at(*column_names)
  		end
		end
  end

	def self.import(file)
		CSV.foreach(file.path, headers: true, header_converters: :symbol) do |row|
			begin
				r_hash = row.to_hash
				f_url = row[:url].to_s

				p "feed"
				p f_url

	  		f = Feed.find_by(url: f_url) || new
	  		p f.name
				f.attributes = row.to_hash.slice(:name, :url, :auto_public, :primary_role, :email_descript, :firm_name, :follow_url, :description, :default_author, :address)
#				p row.to_hash.slice(:name, :url, :auto_public, :primary_role, :email_descript, :firm_name, :follow_url, :description, :default_author, :address)
#				p "test"
				f.save!
#				p "done"
			rescue Exception => e
				p e.message 
			end
		end
	end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /feeds
  # GET /feeds.json
  def index
    respond_to do |format|
      format.html {
        query = params[:q].presence || "*"
        @feeds = Feed.search(query, order: :name, page: params[:page], per_page: 25)
      }
      format.csv { 
        send_data Feed.to_csv
      }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @categories = Category.where(id: @feed.category_ids)
  end

  # GET /feeds/new
  def new
    if params[:category]
      begin 
        @categories = Category.find(params[:category]).subtree
      rescue
        @categories = nil
      end
    end
    @categories ||= Category.all
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
    if params[:category]
      begin 
        @categories = Category.find(params[:category]).subtree
      rescue
        @categories = nil
      end
    end
    @categories ||= Category.all
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Feed.import(params[:file])
    redirect_to feeds_url, notice: "Feeds imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def feed_params
      params.require(:feed).permit(:name, :url, :auto_public, :primary_role, :votes, :email_descript, :firm_name, :tag_list,  :follow_url, :description, :default_author, :address, :non_investor, category_ids:[])
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :feed_name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :feed_url %>
  </div>

  <div class="field">
    <%= form.label :auto_public %>
    <%= form.check_box :auto_public, id: :feed_auto_public %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tag_list, id: :feed_tags %>
  </div>

  <div class="field">
    <%= form.label :follow_url %>
    <%= form.text_field :follow_url, id: :feed_follow_url %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :feed_description %>
  </div>

  <div class="field">
    <%= form.label :default_author %>
    <%= form.text_field :default_author, id: :feed_default_author %>
  </div>

  <div class="field">
    <%= form.label :primary_role %>
    <%= form.text_field :primary_role, id: :feed_primary_role %>
  </div>

  <div class="field">
    <%= form.label :email_descript %>
    <%= form.text_field :email_descript, id: :feed_email_descript %>
  </div>

    <div class="field">
    <%= form.label :firm_name %>
    <%= form.text_field :firm_name, id: :feed_firm_name %>
  </div>

    <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :feed_address %>
  </div>

<div class="field">
    <%= form.label :votes %>
    <%= form.text_field :votes, id: :feed_votes %>
  </div>

<div class="field">
  <i><small>Check the box below if the writer is not an investment firm or individual investor. Their posts will still be shown in the main feed but will be separately shown on emails tab.</small></i><br>
    Non Core
    <% form.label :non_investor %>
    <%= form.check_box :non_investor, id: :feed_non_investor %>
  </div>

  
<% if !@categories.nil? %>
  <div class="field">
    <b>Associated Categories</b>
    <% form.label :category_ids %>

    <%= form.collection_check_boxes :category_ids, @categories.order(:ordering), :id, :name do |c| %>
      <br>
      <% d = c.object.depth %>
      <% until d <= 0 do %>
      &nbsp;&nbsp;
      <% d = d - 1 %>
      <% end %>
        &nbsp;<%= c.check_box %>
        <%= c.object.name %>     
    <% end %>
  </div>
<% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<div class="container">
	<h1>Editing Feed</h1>

	<%= render 'form', feed: @feed %>

	<%= link_to 'Show', @feed %> |
	<%= link_to 'Back', feeds_path %>
</div>

app/views/feeds/index.html.erb
<section class="bg-white">
  <div class="container">

    <p id="notice"><%= notice %></p>

    <h1>Feeds</h1>

    <a class="typeform-share button inter btn-primary btn" href="https://form.typeform.com/to/Nwe2DSOx" data-mode="drawer_right" style="display:inline-block;text-decoration:none;cursor:pointer;font-family:Helvetica,Arial,sans-serif;text-align:center;margin:0;max-width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-weight:bold;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;" target="_blank">Suggest a feed for addition</a> 
<!-- 
<a class="typeform-share button inter btn-secondary btn" href="https://form.typeform.com/to/Nwe2DSOx" data-mode="drawer_right" style="display:inline-block;text-decoration:none;cursor:pointer;font-family:Helvetica,Arial,sans-serif;text-align:center;margin:0;max-width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-weight:bold;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;" target="_blank">Suggest Modification to a Feed</a> 

<a class="typeform-share button inter btn-danger btn" href="https://form.typeform.com/to/Nwe2DSOx" data-mode="drawer_right" style="display:inline-block;text-decoration:none;cursor:pointer;font-family:Helvetica,Arial,sans-serif;text-align:center;margin:0;max-width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-weight:bold;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;" target="_blank">Request Feed Removal</a> 
-->

<% if user_signed_in? %>
<br><br><%= link_to 'New Feed', new_feed_path %>
<% end %>

</div>
</section>

<section>

    <div class="row">
      <div class="col-sm-4 col-md-3">
        <form>
          <div class="form-group" style="padding:30px;">
            <%= form_tag feeds_path, method: :get do %>
            <%= text_field_tag :q, nil, placeholder: "Search by author or firm", class: "form-control" %>
            <% end %>
            <button type="submit" class="btn btn-primary" style="margin-top:20px;">Search</button>
          </div></form>
        </div>


        <div class="col-sm-9">
          <div class="row">
            <% @feeds.each do |feed| %>
            <div class="col-xs-6 col-sm-6 col-md-4">
              <div class="card hover-effect inter">
                <div class="card-body py-3 news">
                  <h5 class="inter"><%= link_to feed.name, feed.follow_url, target: :_blank %></h5>
                  <div class="mb-4">
                    <p class="inter" style="color:black;"><%= feed.description %></p>
                    <code><%= feed.tag_list %></code>
                  </div>
                </div>
                <div class="card-footer">
                  <div class="d-flex align-items-center">
                    <span class="small">
                      <% if !feed.default_author.blank? %>
                      Primary Author(s): <%= feed.default_author %>
                      <% end %>
                      <% if user_signed_in? %>
                      <%= link_to 'Edit', edit_feed_path(feed) %>
                      | <%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %>
                      <% end %></span>
                    </div>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
          </div>

          <div class="container">
            <div class="center">
              <%= will_paginate @news, previous_label: h("<"), next_label: h(">") %>
            </div>
          </div>
        </div>
      </div>

      <% if user_signed_in? %>
      <div class="row">
        <h5>Import Feeds</h5><br>        
        <%= form_tag import_feeds_path, multipart: true do %>
        <%= file_field_tag :file %><br>
        <%= submit_tag "Import" %>
        <% end %>
      </div>
      <% end %>

    </div>
  
</section>


<script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm_share", b="https://embed.typeform.com/"; if(!gi.call(d,id)){ js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script>

app/views/feeds/new.html.erb
<div class="container">
	<h1>New Feed</h1>

	<%= render 'form', feed: @feed %>

	<%= link_to 'Back', feeds_path %>
</div>

app/views/feeds/show.html.erb
<section class="bg-white">
<p id="notice"><%= notice %></p>

<div class="container">
<h3><%= @feed.name %></h3>

<p>
  <strong>Rss Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Home Page (Follow) URL:</strong>
  <%= @feed.follow_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @feed.description %>
</p>

<p>
  <strong>Email Description:</strong>
  <%= @feed.email_descript %>
</p>

<p>
  <strong>Author Name:</strong>
  <%= @feed.default_author %>
</p>

<p>
  <strong>Firm Name:</strong>
  <%= @feed.firm_name %>
</p>

<p>
  <strong>Auto-public:</strong>
  <%= @feed.auto_public %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @feed.tag_list %>
</p>

<p>
  <strong>Categories:</strong>
  <%= @feed.category_ids %>
</p>

<p>
  <strong>Primary Role:</strong>
  <%= @feed.primary_role %>
</p>

<p>
  <strong>Address + Location:</strong>
  <%= @feed.address %> (<%= @feed.latitude %>, <%= @feed.longitude %>)
</p>

<p>
  <strong>Votes:</strong>
  <%= @feed.votes %>
</p>

<p>
  <strong>Non Core:</strong>
  <%= @feed.non_investor %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

</div>
</section>