config/routes.rb
Rails.application.routes.draw do
  
  resources :leads
  resources :feeds do 
    collection { post :import }
  end

  resources :locations
  resources :app_data
  resources :mobile_apps
  resources :agencies
  resources :domain_alexas
  resources :news
  resources :companies do 
    collection { post :import }
  end
  resources :categories
  resources :domains do 
    collection { post :import }
    collection { get :autocomplete }
  end
  resources :daycares
  resources :blogs
  resources :linkedin_counts do
    collection { post :import }
  end
  ActiveAdmin.routes(self)
  devise_for :users

  as :user do
  	get "signin" => 'devise/sessions#new'
  	delete "signout" => 'devise/sessions#destroy'
  	get "signup" => 'devise/registrations#new'
  end

  root 'pages#home'

  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'
  get 'uploads' => 'pages#uploads'
  get 'talent' => 'pages#talent'

  get 'emails' => 'pages#emails'

  get 'sitemap' => 'pages#sitemap'
  get 'for_providers' => 'pages#for_providers'
  get 'dashboard' => 'pages#dashboard'
  get 'privacy_policy' => 'pages#privacy_policy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'loaderio-5d6ea8f06b52a5188451d2d277efab90' => 'pages#loader'

end

app/models/agency.rb
class Agency < ApplicationRecord
	has_and_belongs_to_many :categories
	#friendly_id :name, use: :slugged

	validates :domain, presence: true
	validates :domain, uniqueness: true

	before_save do
  	self.domain = sanitize_url(domain)
	end

	before_create do
  	self.domain = sanitize_url(domain)
	end

	def sanitize_url(domain)
    domain.gsub!("https://", "")
    domain.gsub!("http://", "")
    domain.gsub!("www.", "")
    domain = domain.split("?")[0]
    domain = domain.split("/")[0]
    domain
	end

end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  include ApplicationHelper
  before_action :set_agency, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.all
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
    @categories = Category.where(id: @agency.category_ids)
  end

  # GET /agencies/new
  def new
    @categories = Category.find_by(name: "Agency")
    if !@categories.nil?
      @categories = @categories.subtree
    end
    @agency = Agency.new
  end

  # GET /agencies/1/edit
  def edit
    @categories = Category.find_by(name: "Agency")
    if !@categories.nil?
      @categories = @categories.subtree
    end
  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(agency_params)
    @url = sanitize_url(@agency.domain)

    AgencyEnrichJob.set(wait: 5).perform_later(@url)

    respond_to do |format|
      if @agency.save
        format.html { redirect_to @agency, notice: 'Agency was successfully created.' }
        format.json { render :show, status: :created, location: @agency }
      else
        format.html { render :new }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agencies/1
  # PATCH/PUT /agencies/1.json
  def update
    respond_to do |format|
      if @agency.update(agency_params)
        format.html { redirect_to @agency, notice: 'Agency was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency }
      else
        format.html { render :edit }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency.destroy
    respond_to do |format|
      format.html { redirect_to agencies_url, notice: 'Agency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def agency_params
      params.require(:agency).permit(:name, :image_url, :logo_url, :domain, :type, :clients, :linkedin_url, :employee_count, :description, :year_founded, :location, category_ids:[])
    end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/_form.html.erb
<div class="container">
<%= form_with(model: agency, local: true) do |form| %>
  <% if agency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agency.errors.count, "error") %> prohibited this agency from being saved:</h2>

      <ul>
      <% agency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :agency_name %>
  </div>

  <div class="field">
    <%= form.label :domain %>
    <%= form.text_field :domain, id: :agency_domain %>
  </div>

  <div class="field">
    <%= form.label :linkedin_url %>
    <%= form.text_field :linkedin_url, id: :agency_linkedin_url %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :agency_description %>
  </div>

<% if !@categories.nil? %>
    <div class="field">
    <%= form.label :category_ids %>

    <%= form.collection_check_boxes :category_ids, @categories.order(:ordering), :id, :name do |c| %>
      <br>
      <% d = c.object.depth %>
      <% until d <= 0 do %>
      &nbsp;&nbsp;
      <% d = d - 1 %>
      <% end %>
        &nbsp;<%= c.check_box %>
        <%= c.object.name %>
     
    <% end %>
  </div>
<% end %>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :agency_location %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :agency_image_url %>
  </div>

  <div class="field">
    <%= form.label :logo_url %>
    <%= form.text_field :logo_url, id: :agency_logo_url %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :agency_type %>
  </div>

  <div class="field">
    <%= form.label :clients %>
    <%= form.text_field :clients, id: :agency_clients %>
  </div>

  <div class="field">
    <%= form.label :year_founded %>
    <%= form.text_field :year_founded, id: :agency_year_founded %>
  </div>
 
  <div class="field">
    <%= form.label :employee_count %>
    <%= form.text_field :employee_count, id: :agency_employee_count %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/agencies/edit.html.erb
<div class="container">
<h1>Editing Agency</h1>

<%= render 'form', agency: @agency %>

<%= link_to 'Show', @agency %> |
<%= link_to 'Back', agencies_path %>
</div>

app/views/agencies/index.html.erb
<section class="bg-white">
  <div class="container">
    <h1>Agencies</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Image url</th>
          <th>Logo url</th>
          <th>Domain</th>
          <th>Type</th>
          <th>Clients</th>
          <% if user_signed_in? %>
          <th colspan="2"></th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @agencies.each do |agency| %>
        <tr>
          <td><%= link_to agency.name, agency %></td>
          <td><%= agency.image_url %></td>
          <td><%= agency.logo_url %></td>
          <td><%= agency.domain %></td>
          <td><%= agency.type %></td>
          <td><%= agency.clients %></td>
          <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_agency_path(agency) %></td>
          <td><%= link_to 'Destroy', agency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to 'New Agency', new_agency_path, class: "btn btn-primary" %>
  </section>

  <section>
    <div class="container">
      <div class="row">
        <% @agencies.each do |agency| %>
        <div class="col-xs-6 col-sm-4 col-md-3">
          <div class="card hover-effect">
            <!-- <img class="card-img-top" src="assets/images/shifts.png" alt="Modular Structure" />--> 
            <div class="center" style="max-height:200px; background:#dcdde1;">
            <%= image_tag "https://logo.clearbit.com/#{agency.domain}", class: "card-img-top", style: "padding:10px; max-height:180px; width:auto" %>
            </div>

            <div class="card-body py-3">
              <h5><%= link_to agency.name, agency %></h5>
              <div class="mb-4">
                <p class="inter" style="color:black;">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti.</p>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>

  </div>
</section>

app/views/agencies/new.html.erb
<div class="container">
<h1>New Agency</h1>

<%= render 'form', agency: @agency %>

<%= link_to 'Back', agencies_path %>
</div>

app/views/agencies/show.html.erb
<div class="container">
<p>
  <strong>Name:</strong>
  <%= @agency.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @agency.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @agency.image_url %>
</p>

<p>
  <strong>Categories:</strong>
  <% @categories.each do |c| %>
    <%= link_to c.name, c %>
  <% end %>
</p>

<p>
  <strong>Logo url:</strong>
  <%= @agency.logo_url %>
</p>

<p>
  <strong>Domain:</strong>
  <%= @agency.domain %>
</p>

<p>
  <strong>Type:</strong>
  <%= @agency.type %>
</p>

<p>
  <strong>Clients:</strong>
  <%= @agency.clients %>
</p>

<p>
  <strong>LinkedIn Url</strong>
  <%= @agency.linkedin_url %>
</p>

<p>
  <strong>LinkedIn Url</strong>
  <%= @agency.location %>
</p>

<p>
  <strong>Employee Count:</strong>
  <%= @agency.employee_count %>
</p>

<p>
  <strong>Year Founded:</strong>
  <%= @agency.year_founded %>
</p>

<%= link_to 'Edit', edit_agency_path(@agency) %> |
<%= link_to 'Back', agencies_path %>
</div>