config/routes.rb
Rails.application.routes.draw do
  
  resources :leads
  resources :feeds do 
    collection { post :import }
  end

  resources :locations
  resources :app_data
  resources :mobile_apps
  resources :agencies
  resources :domain_alexas
  resources :news
  resources :companies do 
    collection { post :import }
  end
  resources :categories
  resources :domains do 
    collection { post :import }
    collection { get :autocomplete }
  end
  resources :daycares
  resources :blogs
  resources :linkedin_counts do
    collection { post :import }
  end
  ActiveAdmin.routes(self)
  devise_for :users

  as :user do
  	get "signin" => 'devise/sessions#new'
  	delete "signout" => 'devise/sessions#destroy'
  	get "signup" => 'devise/registrations#new'
  end

  root 'pages#home'

  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'
  get 'uploads' => 'pages#uploads'
  get 'talent' => 'pages#talent'

  get 'emails' => 'pages#emails'

  get 'sitemap' => 'pages#sitemap'
  get 'for_providers' => 'pages#for_providers'
  get 'dashboard' => 'pages#dashboard'
  get 'privacy_policy' => 'pages#privacy_policy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'loaderio-5d6ea8f06b52a5188451d2d277efab90' => 'pages#loader'

end

app/models/domain_alexa.rb
class DomainAlexa < ApplicationRecord
	belongs_to :domain
end

app/controllers/domain_alexas_controller.rb
class DomainAlexasController < ApplicationController
  before_action :set_domain_alexa, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /domain_alexas
  # GET /domain_alexas.json
  def index
    @domain_alexas = DomainAlexa.all
  end

  # GET /domain_alexas/1
  # GET /domain_alexas/1.json
  def show
    if @domain_alexa.date.nil?
      @domain_alexa.date = @domain_alexa.created_at
      @domain_alexa.save
    end
  end

  # GET /domain_alexas/new
  def new
    @domain_alexa = DomainAlexa.new
  end

  # GET /domain_alexas/1/edit
  def edit
  end

  # POST /domain_alexas
  # POST /domain_alexas.json
  def create
    @domain_alexa = DomainAlexa.new(domain_alexa_params)

    respond_to do |format|
      if @domain_alexa.save
        format.html { redirect_to @domain_alexa, notice: 'Domain alexa was successfully created.' }
        format.json { render :show, status: :created, location: @domain_alexa }
      else
        format.html { render :new }
        format.json { render json: @domain_alexa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domain_alexas/1
  # PATCH/PUT /domain_alexas/1.json
  def update
    respond_to do |format|
      if @domain_alexa.update(domain_alexa_params)
        format.html { redirect_to @domain_alexa, notice: 'Domain alexa was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain_alexa }
      else
        format.html { render :edit }
        format.json { render json: @domain_alexa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domain_alexas/1
  # DELETE /domain_alexas/1.json
  def destroy
    @domain_alexa.destroy
    respond_to do |format|
      format.html { redirect_to domain_alexas_url, notice: 'Domain alexa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain_alexa
      @domain_alexa = DomainAlexa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domain_alexa_params
      params.require(:domain_alexa).permit(:domain_url, :alexa_rank, :reach_rank_value, :reach_per_million_value, :page_views_rank_value, :page_views_per_million_value, :page_views_per_user_value, :domain_id)
      date

    end
end

app/helpers/domain_alexas_helper.rb
module DomainAlexasHelper
end

app/views/domain_alexas/_form.html.erb
<%= form_with(model: domain_alexa, local: true) do |form| %>
  <% if domain_alexa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(domain_alexa.errors.count, "error") %> prohibited this domain_alexa from being saved:</h2>

      <ul>
      <% domain_alexa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :domain_id %>
    <%= form.number_field :domain_id, id: :domain_alexa_domain_id %>
  </div>

  <div class="field">
    <%= form.label :domain_url %>
    <%= form.text_field :domain_url, id: :domain_alexa_domain_url %>
  </div>

  <div class="field">
    <%= form.label :alexa_rank %>
    <%= form.number_field :alexa_rank, id: :domain_alexa_alexa_rank %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/domain_alexas/edit.html.erb
<h1>Editing Domain Alexa</h1>

<%= render 'form', domain_alexa: @domain_alexa %>

<%= link_to 'Show', @domain_alexa %> |
<%= link_to 'Back', domain_alexas_path %>

app/views/domain_alexas/index.html.erb
<div class="container">
  <h1>Domain Alexas</h1>

  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Domain Id</th>
        <th>Domain</th>
        <th>Alexa rank</th>
        <th>Reach Rank</th>
        <th>Reach PerMillion</th>
        <th>Page Views Rank</th>
        <th>Page Views PerMillion</th>
        <th>Page Views PerUser</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @domain_alexas.each do |domain_alexa| %>
        <tr>
          <td><%= domain_alexa.date %></td>
          <td><%= domain_alexa.domain_id %></td>
          <td><%= domain_alexa.domain_url %></td>
          <td><%= domain_alexa.alexa_rank %></td>
          <td><%= domain_alexa.reach_rank_value %></td>
          <td><%= domain_alexa.reach_per_million_value %></td>
          <td><%= domain_alexa.page_views_rank_value %></td>
          <td><%= domain_alexa.page_views_per_million_value %></td>
          <td><%= domain_alexa.page_views_per_user_value %></td>
          <td><%= link_to 'Show', domain_alexa %></td>
          <td><%= link_to 'Edit', edit_domain_alexa_path(domain_alexa) %></td>
          <td><%= link_to 'Destroy', domain_alexa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Domain Alexa', new_domain_alexa_path %>
</div>

app/views/domain_alexas/new.html.erb
<h1>New Domain Alexa</h1>

<%= render 'form', domain_alexa: @domain_alexa %>

<%= link_to 'Back', domain_alexas_path %>

app/views/domain_alexas/show.html.erb
<div class="container">
<p>
  <strong>Domain Id:</strong>
  <%= @domain_alexa.domain_id %>
</p>

<p>
  <strong>Domain URL:</strong>
  <%= @domain_alexa.domain_url %>
</p>

<p>
  <strong>Alexa rank:</strong>
  <%= @domain_alexa.alexa_rank %>
</p>

<p>
  <strong>Date:</strong>
  <%= @domain_alexa.date %>
</p>

<p>
  <strong>Reach Rank:</strong>
  <%= @domain_alexa.reach_rank_value %>
</p>

<p>
  <strong>Reach PerMillion:</strong>
  <%= @domain_alexa.reach_per_million_value %>
</p>

<p>
  <strong>Page Views Rank:</strong>
  <%= @domain_alexa.page_views_rank_value %>
</p>

<p>
  <strong>Page Views PerMillion:</strong>
  <%= @domain_alexa.page_views_per_million_value %>
</p>

<p>
  <strong>Page Views PerUser:</strong>
  <%= @domain_alexa.page_views_per_user_value %>
</p>

<%= link_to 'Edit', edit_domain_alexa_path(@domain_alexa) %> |
<%= link_to 'Back', domain_alexas_path %>
</div>