config/routes.rb
Rails.application.routes.draw do
  
  resources :leads
  resources :feeds do 
    collection { post :import }
  end

  resources :locations
  resources :app_data
  resources :mobile_apps
  resources :agencies
  resources :domain_alexas
  resources :news
  resources :companies do 
    collection { post :import }
  end
  resources :categories
  resources :domains do 
    collection { post :import }
    collection { get :autocomplete }
  end
  resources :daycares
  resources :blogs
  resources :linkedin_counts do
    collection { post :import }
  end
  ActiveAdmin.routes(self)
  devise_for :users

  as :user do
  	get "signin" => 'devise/sessions#new'
  	delete "signout" => 'devise/sessions#destroy'
  	get "signup" => 'devise/registrations#new'
  end

  root 'pages#home'

  get 'about' => 'pages#about'
  get 'terms' => 'pages#terms'
  get 'uploads' => 'pages#uploads'
  get 'talent' => 'pages#talent'

  get 'emails' => 'pages#emails'

  get 'sitemap' => 'pages#sitemap'
  get 'for_providers' => 'pages#for_providers'
  get 'dashboard' => 'pages#dashboard'
  get 'privacy_policy' => 'pages#privacy_policy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'loaderio-5d6ea8f06b52a5188451d2d277efab90' => 'pages#loader'

end

app/models/category.rb
class Category < ApplicationRecord
	extend FriendlyId
	has_ancestry

	has_many :domain_categories
	has_many :domains, through: :domain_categories
	accepts_nested_attributes_for :domain_categories

	has_many :companies
	has_and_belongs_to_many :agencies
	has_and_belongs_to_many :mobile_apps

	friendly_id :name, use: :slugged


	has_and_belongs_to_many :feeds
	has_and_belongs_to_many :news

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.arrange(:order => :ordering)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    descendant_ids = @category.descendant_ids
    descendant_ids.append(@category.id)

    # @news = 

    # @domains = Domain.joins(:categories).where(category_id: descendant_ids)
    @domains = Domain.joins(:categories).where(categories: {id: descendant_ids}).order(:alexa_rank)
    @domains = @domains.uniq
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
    ReorderCategoriesJob.set(wait: 3).perform_later()
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
    ReorderCategoriesJob.set(wait: 3).perform_later()
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
    ReorderCategoriesJob.set(wait: 3).perform_later()
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :parent_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="field">
    <%= form.label :parent_id %>
    <%= form.collection_select :parent_id, Category.order(:name) , :id, :name, include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container">

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ancestry</th>
      <th>Ordering</th>
      <% if user_signed_in? %>
      <th colspan="2"></th>
      <% end %> 
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category, cat2| %>
      <tr>
        <td><%= link_to category.name, category %></td>
        <td><%= category.ancestry %></td>
        <td><%= category.ordering %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
        <% category.descendants.each do |cat2, child| %>
        <tr> 
          <td>
          <% i = cat2.depth %>
          <% while i > 0 %>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <% i = i-1 %>
          <% end %>
          &bull;&nbsp;
          <%= link_to cat2.name, cat2 %></td>

            <td><%= cat2.ancestry %></td>
            <td><%= cat2.ordering %></td>
            <% if user_signed_in? %>
            <td><%= link_to 'Edit', edit_category_path(cat2) %></td>
            <td><%= link_to 'Destroy', cat2, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
    <% end %>
    <tr>
        <td><%= link_to "Uncategorized", domains_path(:uncategorized => true) %></td>
      </tr>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Category', new_category_path, class: "btn btn-lg btn-primary" %>
  <br><br>
<% end %>

</div>

app/views/categories/new.html.erb
<div class="container">
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<section style="background:black;">
      <div class="container height-lg-10">
        <div class="row">
          <div class="col-md-8 col-lg-7 col-xl-6">
            <nav aria-label="breadcrumb">
              <p>
                <% @category.ancestors.each do |top_cat| %>
                  <%= link_to top_cat.name, top_cat %> / 
                <% end %>
              </p>
            </nav>
            <h1 class="display-4 text-white">
              <%= @category.name %> (<%= @category.id %>)
            </h1>
          <!-- <p class="lead mb-0 text-white"></p>-->
          </div>
        </div>
      </div>
</section>

<div class="center">
<% if user_signed_in? %>
  <%= link_to 'New Category', new_category_path, class: "btn btn-primary" %> &bull; 
  <%= link_to 'New Domain', new_domain_path(:category => @category.id), class: "btn btn-secondary" %>
  <br><br>
<% end %>
</div>

<% if user_signed_in? %>
<%= link_to 'Destroy', @category, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>
<br><br>

<% end %>
</div>